import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin User',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John Doe',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'MacBook Pro M2 14-inch',
      slug: 'macbook-pro-m2',
      category: 'Laptops',
      image: 'https://images.unsplash.com/photo-1611186871525-5c33f5e1c22d?w=500&auto=format',
      images: [],
      price: 1999,
      countInStock: 15,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 240,
      description: 'Supercharged by M2 Pro chip. Up to 22 hours of battery life. Up to 96GB unified memory. Stunning Liquid Retina XDR display. Ideal for pro workflows.',
      featured: true,
    },
    {
      name: 'iPhone 15 Pro Max',
      slug: 'iphone-15-pro-max',
      category: 'Smartphones',
      image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500&auto=format',
      images: [],
      price: 1199,
      countInStock: 20,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 890,
      description: 'Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
      featured: true,
    },
    {
      name: 'Sony WH-1000XM5',
      slug: 'sony-wh-1000xm5',
      category: 'Headphones',
      image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500&auto=format',
      images: [],
      price: 349,
      countInStock: 35,
      brand: 'Sony',
      rating: 4.7,
      numReviews: 1024,
      description: 'Industry leading noise cancellation with Auto NC Optimizer. Up to 30-hour battery life. Ultra-lightweight with a redesigned headband for premium comfort.',
      featured: true,
    },
    {
      name: 'iPad Air (5th Gen)',
      slug: 'ipad-air-5',
      category: 'Tablets',
      image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500&auto=format',
      images: [],
      price: 749,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 450,
      description: 'Light. Bright. Full of might. Powered by Apple M1 chip. 10.9-inch Liquid Retina display. USB-C connector. Works with Apple Pencil and Smart Keyboard Folio.',
      featured: false,
    },
    {
      name: 'Samsung 65" QLED 4K TV',
      slug: 'samsung-65-qled-4k-tv',
      category: 'TVs',
      image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format',
      images: [],
      price: 1299,
      countInStock: 8,
      brand: 'Samsung',
      rating: 4.6,
      numReviews: 320,
      description: 'Quantum Dot technology displays over a billion shades of brilliant color. 4K AI Upscaling enhances every scene to near 4K resolution. Quantum HDR+ delivers incredible contrast.',
      featured: true,
    },
    {
      name: 'Dell XPS 15 Laptop',
      slug: 'dell-xps-15',
      category: 'Laptops',
      image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format',
      images: [],
      price: 1799,
      countInStock: 12,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 178,
      description: "Dell's most popular laptop redefined. 15.6-inch OLED display, 13th Gen Intel Core i7 processor, NVIDIA GeForce RTX 4060, perfect for content creators.",
      featured: false,
    },
    {
      name: 'Apple Watch Ultra 2',
      slug: 'apple-watch-ultra-2',
      category: 'Wearables',
      image: 'https://images.unsplash.com/photo-1523475496153-3e2edbb81854?w=500&auto=format',
      images: [],
      price: 799,
      countInStock: 25,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 567,
      description: 'The most rugged and capable Apple Watch. 49mm titanium case. 60-hour battery in Low Power Mode. Precision dual-frequency GPS. Watertight to 100 meters.',
      featured: true,
    },
    {
      name: 'PS5 DualSense Controller',
      slug: 'ps5-dualsense-controller',
      category: 'Gaming',
      image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500&auto=format',
      images: [],
      price: 69.99,
      countInStock: 50,
      brand: 'Sony',
      rating: 4.7,
      numReviews: 2100,
      description: 'Experience a new era of gaming with the DualSense wireless controller. Haptic feedback. Adaptive triggers. Built-in microphone. Immersive feel of the PS5.',
      featured: false,
    },
  ],
};

export default data;
